#baseURL: https://cocky-lichterman-75a7f5.netlify.com/
baseURL: http://localhost:1313
footnoteReturnLinkContents: ↩
theme: gohugo-theme-ananke
MetaDataFormat: "yaml"
DefaultContentLanguage: "en"
SectionPagesMenu: "main"
#Paginate: 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT: true

params:
  AuthorName: PixelPusher
  GitHubUser: PixelPushingPunk
  SidebarRecentLimit: 5
  Subtitle: Digital Forest rules!
  description: The future is here.
  facebook: "#"
  twitter: "#"
  background_color_class: "bg-black"
  featured_image: "/images/home-bg.jpg"
  recent_posts_number: 3

permalinks:
  post: /:year/:month/:title/
title: Digital Forest
